sonata_user:
    security_acl: false
    manager_type: orm # can be orm or mongodb
    impersonating:
        route: sonata_admin_dashboard

sonata_block:
    blocks:
        #...
        sonata.user.block.menu:    # used to display the menu in profile pages
        sonata.user.block.account: # used to display menu option (login option)
        sonata.block.service.text: # used to if you plan to use Sonata user routes
