sonata_admin:
    options: 
        html5_validate: false
    title: %project_name%
    title_logo: /bundles/sonataadmin/logo_title.png
    templates:
        layout:              AppBundle::standard_layout.html.twig
        search:              SonataAdminBundle:Core:search.html.twig
        search_result_block: SonataAdminBundle:Block:block_search_result.html.twig
    security:
        handler: sonata.admin.security.handler.role

        # acl security information
        information:
            LIST:       LIST
            CREATE:     CREATE
            EDIT:       EDIT
            VIEW:       VIEW
            EXPORT:     EXPORT
            
        # permissions not related to an object instance and also to be available when objects do not exist
        # the DELETE admin permission means the user is allowed to batch delete objects
        admin_permissions: [CREATE, LIST, DELETE, UNDELETE, EXPORT, OPERATOR, MASTER]

        # permission related to the objects
        object_permissions: [VIEW, EDIT, DELETE, UNDELETE, OPERATOR, MASTER, OWNER]
        
    dashboard:
        groups:
            sonata_user:
                roles: [ROLE_ADMIN]
                label: 'Seguridad y acceso'
                icon:   '<i class="fa fa-user"></i>'
            admin:
                roles: [ROLE_ADMIN]
                label: 'Admin'
                icon:   '<i class="fa fa-cog"></i>'
            security:
                roles: [ROLE_ADMIN]
                label: 'Oauth'
                icon:   '<i class="fa fa-lock"></i>'
        
        blocks:
            - { position: left,  type: sonata.admin.block.admin_list, settings: { groups: [sonata_user, admin] }}
            #- { position: left,  type: sonata.block.service.reportes}
            - { position: right,  type: sonata.admin.block.admin_list, settings: { groups: [security] } }
