services:
    app.form.registration:
        class: AppBundle\Form\RegistrationType
        tags:
            - { name: form.type, alias: app_user_registration }
            
    app.registro_handler:
        class: AppBundle\Handler\RegistroHandler
        arguments: ['@router','@service_container', '@session']
        tags:
            - { name: kernel.event_subscriber }
