<?php

namespace AppBundle\DataFixtures\ORM;

use AppBundle\Entity\Pais;
use Doctrine\Common\DataFixtures\AbstractFixture;
use Doctrine\Common\DataFixtures\FixtureInterface;
use Doctrine\Common\DataFixtures\OrderedFixtureInterface;
use Doctrine\Common\Persistence\ObjectManager;
use Symfony\Component\DependencyInjection\ContainerAwareInterface;
use Symfony\Component\DependencyInjection\ContainerInterface;

class PaisesData extends AbstractFixture implements FixtureInterface, ContainerAwareInterface, OrderedFixtureInterface {

    /**
     * @var ContainerInterface
     */
    private $container;

    /**
     * {@inheritDoc}
     */
    public function setContainer(ContainerInterface $container = null) {
        $this->container = $container;
    }

    public function getOrder() {
        return 3;
    }

    public function load(ObjectManager $manager) {
        $paises = [
            "AL" => "Albania",
            "DE" => "Alemania",
            "AD" => "Andorra",
            "AM" => "Armenia",
            "AT" => "Austria",
            "AZ" => "Azerbaiyán",
            "BE" => "Bélgica",
            "BY" => "Bielorrusia",
            "BA" => "Bosnia y Herzegovina",
            "BG" => "Bulgaria",
            "CY" => "Chipre",
            "VA" => "Ciudad del Vaticano (Santa Sede)",
            "HR" => "Croacia",
            "DK" => "Dinamarca",
            "SK" => "Eslovaquia",
            "SI" => "Eslovenia",
            "ES" => "España",
            "EE" => "Estonia",
            "FI" => "Finlandia",
            "FR" => "Francia",
            "GE" => "Georgia",
            "GR" => "Grecia",
            "HU" => "Hungría",
            "IE" => "Irlanda",
            "IS" => "Islandia",
            "IT" => "Italia",
            "XK" => "Kosovo",
            "LV" => "Letonia",
            "LI" => "Liechtenstein",
            "LT" => "Lituania",
            "LU" => "Luxemburgo",
            "MK" => "Macedonia, República de",
            "MT" => "Malta",
            "MD" => "Moldavia",
            "MC" => "Mónaco",
            "ME" => "Montenegro",
            "NO" => "Noruega",
            "NL" => "Países Bajos",
            "PL" => "Polonia",
            "PT" => "Portugal",
            "UK" => "Reino Unido",
            "CZ" => "República Checa",
            "RO" => "Rumanía",
            "RU" => "Rusia",
            "SM" => "San Marino",
            "SE" => "Suecia",
            "CH" => "Suiza",
            "TR" => "Turquía",
            "UA" => "Ucrania",
            "YU" => "Yugoslavia",
            "AO" => "Angola",
            "DZ" => "Argelia",
            "BJ" => "Benín",
            "BW" => "Botswana",
            "BF" => "Burkina Faso",
            "BI" => "Burundi",
            "CM" => "Camerún",
            "CV" => "Cabo Verde",
            "TD" => "Chad",
            "KM" => "Comores",
            "CG" => "Congo",
            "CD" => "Congo, República Democrática del",
            "CI" => "Costa de Marfil",
            "EG" => "Egipto",
            "ER" => "Eritrea",
            "ET" => "Etiopía",
            "GA" => "Gabón",
            "GM" => "Gambia",
            "GH" => "Ghana",
            "GN" => "Guinea",
            "GW" => "Guinea Bissau",
            "GQ" => "Guinea Ecuatorial",
            "KE" => "Kenia",
            "LS" => "Lesoto",
            "LR" => "Liberia",
            "LY" => "Libia",
            "MG" => "Madagascar",
            "MW" => "Malawi",
            "ML" => "Malí",
            "MA" => "Marruecos",
            "MU" => "Mauricio",
            "MR" => "Mauritania",
            "MZ" => "Mozambique",
            "NA" => "Namibia",
            "NE" => "Níger",
            "NG" => "Nigeria",
            "CF" => "República Centroafricana",
            "ZA" => "República de Sudáfrica",
            "RW" => "Ruanda",
            "EH" => "Sahara Occidental",
            "ST" => "Santo Tomé y Príncipe",
            "SN" => "Senegal",
            "SC" => "Seychelles",
            "SL" => "Sierra Leona",
            "SO" => "Somalia",
            "SD" => "Sudán",
            "SS" => "Sudán del Sur",
            "SZ" => "Suazilandia",
            "TZ" => "Tanzania",
            "TG" => "Togo",
            "TN" => "Túnez",
            "UG" => "Uganda",
            "DJ" => "Yibuti",
            "ZM" => "Zambia",
            "ZW" => "Zimbabue",
            "AU" => "Australia",
            "FM" => "Micronesia, Estados Federados de",
            "FJ" => "Fiji",
            "KI" => "Kiribati",
            "MH" => "Islas Marshall",
            "SB" => "Islas Salomón",
            "NR" => "Nauru",
            "NZ" => "Nueva Zelanda",
            "PW" => "Palaos",
            "PG" => "Papúa Nueva Guinea",
            "WS" => "Samoa",
            "TO" => "Tonga",
            "TV" => "Tuvalu",
            "VU" => "Vanuatu",
            "AR" => "Argentina",
            "BO" => "Bolivia",
            "BR" => "Brasil",
            "CL" => "Chile",
            "CO" => "Colombia",
            "EC" => "Ecuador",
            "GY" => "Guayana",
            "PY" => "Paraguay",
            "PE" => "Perú",
            "SR" => "Surinam",
            "TT" => "Trinidad y Tobago",
            "UY" => "Uruguay",
            "VE" => "Venezuela",
            "AG" => "Antigua y Barbuda",
            "BS" => "Bahamas",
            "BB" => "Barbados",
            "BZ" => "Belice",
            "CA" => "Canadá",
            "CR" => "Costa Rica",
            "CU" => "Cuba",
            "DM" => "Dominica",
            "SV" => "El Salvador",
            "US" => "Estados Unidos",
            "GD" => "Granada",
            "GT" => "Guatemala",
            "HT" => "Haití",
            "HN" => "Honduras",
            "JM" => "Jamaica",
            "MX" => "México",
            "NI" => "Nicaragua",
            "PA" => "Panamá",
            "PR" => "Puerto Rico",
            "DO" => "República Dominicana",
            "KN" => "San Cristóbal y Nieves",
            "VC" => "San Vicente y Granadinas",
            "LC" => "Santa Lucía",
            "AF" => "Afganistán",
            "SA" => "Arabia Saudí",
            "BH" => "Baréin",
            "BD" => "Bangladesh",
            "MM" => "Birmania",
            "BT" => "Bután",
            "BN" => "Brunéi",
            "KH" => "Camboya",
            "CN" => "China",
            "KP" => "Corea, República Popular Democrática de",
            "KR" => "Corea, República de",
            "AE" => "Emiratos Árabes Unidos",
            "PH" => "Filipinas",
            "IN" => "India",
            "ID" => "Indonesia",
            "IQ" => "Iraq",
            "IR" => "Irán",
            "IL" => "Israel",
            "JP" => "Japón",
            "JO" => "Jordania",
            "KZ" => "Kazajistán",
            "KG" => "Kirguizistán",
            "KW" => "Kuwait",
            "LA" => "Laos",
            "LB" => "Líbano",
            "MY" => "Malasia",
            "MV" => "Maldivas",
            "MN" => "Mongolia",
            "NP" => "Nepal",
            "OM" => "Omán",
            "PK" => "Paquistán",
            "QA" => "Qatar",
            "SG" => "Singapur",
            "SY" => "Siria",
            "LK" => "Sri Lanka",
            "TJ" => "Tayikistán",
            "TH" => "Tailandia",
            "TP" => "Timor Oriental",
            "TM" => "Turkmenistán",
            "UZ" => "Uzbekistán",
            "VN" => "Vietnam",
            "YE" => "Yemen",
        ];
        $em = $this->container->get('doctrine')->getManager();
        foreach ($paises as $sigla => $pais) {
            $registro = $em->getRepository('AppBundle:Pais')->findOneBy(array('nombre' => $pais));
            if (!$registro) {
                $entity = new Pais();
                $entity->setNombre($pais);
                $entity->setSigla($sigla);
                $manager->persist($entity);
            }
        }
        $manager->flush();
    }

}
