<?php

namespace Application\Sonata\UserBundle\Repository;

use Doctrine\ORM\EntityRepository;

use ITO\LogicBundle\Entity\Coordinador;

/**
 * ProfileRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository {
    public function findUserInstaladores($coordinador = null) {
        $em = $this->getEntityManager();
        
        $query2 = $em->getRepository("ApplicationSonataUserBundle:User")
            ->createQueryBuilder("s_u")
            ->select("s_u.id")
            ->where("s_u INSTANCE OF ITOLogicBundle:Instalador");
        
        $query = $em->getRepository("ITOLogicBundle:Instalador")
                ->createQueryBuilder("i");
        
        $query->where($query->expr()->in("i.id", $query2->getDQL()));
        
        if($coordinador && $coordinador instanceof Coordinador){
            $query
                ->leftJoin("i.instalaciones", "ins")
                ->leftJoin("ins.municipio", "m")
                ->leftJoin("m.coordinadores", "c")
                ->Andwhere("c.id = :coordinador")
                ->setParameter("coordinador", $coordinador->getId());
        }
        
        return $query;
    }
    
    public function buscarCampoUnico($campo, $valor, $id) {
        $em = $this->getEntityManager();
        
        $query = $em->getRepository("ApplicationSonataUserBundle:User")
            ->createQueryBuilder("u")
            ->where("u." . $campo . " = :valor")
            ->setParameter("valor", $valor)
            ->setMaxResults(1);
        
        if($id){
            $query
                ->andWhere("u.id <> :id")
                ->setParameter("id", $id);
        }
            
        return $query->getQuery()->getResult();
    }
}
